### ISSUE TITLE
Software Requirements Specification

### ISSUE THREAD

**Issue by greadvx** [Shalynishka/ExRates#2]
Пункт [3.2.1.1 Удобства использования](https://github.com/Shalynishka/ExRates/blob/master/docs/Requirements.md#3.2.1.1)
Что подразумевает собой удобный и понятный интерфейс?
Несоответствие характеристикам качественных требований.

**Comment by greadvx** [comment]
Пункт [2.3 Характеристики пользователей](
https://github.com/Shalynishka/ExRates/blob/master/docs/Requirements.md#2.3)
Какая целевая аудитория приложения?
Какой уровень технической грамотности необходим пользователю?
Пункт [3.2.1.2 Достоверность информации](
https://github.com/Shalynishka/ExRates/blob/master/docs/Requirements.md#3.2.1.2)
Что подразумевается в данном пункте?
Как это проверить?

**Comment by Shalynishka** [comment]
Спасибо за замечания, ошибки учтены и исправлены.
